#!/usr/bin/env zsh
mkdir -p $HOME/.config/zsh
cp .zshrc $HOME

cp path.zsh $HOME/.config/zsh
cp plugins.zsh $HOME/.config/zsh
cp prompt.zsh $HOME/.config/zsh

cp -r plugins $HOME/.config/zsh

touch $HOME/ZSH_LOAD_PLUGINS

source $HOME/.zshrc
